let token =
	'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImZpcnN0TmFtZSI6IkNoaWtlIiwibGFzdE5hbWUiOiJVY2hla2EiLCJ1c2VyTmFtZSI6IkFkbWluIiwiZW1haWwiOiJ3aWxzb25hY2hpdmVyQGdtYWlsLmNvbSIsImlhdCI6MTU3MzU5NDMzMiwiZXhwIjoxNTc0MTk5MTMyfQ.zb-hGnK-YeayOgujvetUL3VeH3EWlIY9LfHaKlLnTN4';

export default token;
