const token =	'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZpcnN0TmFtZSI6IkNoaWtlIiwibGFzdE5hbWUiOiJVY2hla2EiLCJ1c2VyTmFtZSI6IkFkbWluIiwiZW1haWwiOiJyeWFudWNoZWthQGdtYWlsLmNvbSIsImlhdCI6MTU3MzcyMjQ3NCwiZXhwIjoxNTc0MzI3Mjc0fQ.P_pddPkN76FxwSSqZGzFs99f5QzHsRvAqse97mub884';

export default token;
