language: node_js
node_js:
  - '8.11.2'
env:
  global:
  - NODE_ENV=test
notifications:
  - email:false
services:
  - postgresql
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - psql -c 'create database test_database;' -U postgres
  - psql -c 'create user chike with password null;' -U postgres
script:
  - npm run test
after_script: 
  - npm run coverage
deploy:
  provider: heroku
  api_key:
    production:
      secure: "bbc9447f-e674-46d9-b55b-8eafc2b2d284"
  app:
    develop: teamwork-lite