language: node_js
node_js:
  - '8.11.2'
services:
  - postgresql
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create user Chike with password null;' -U postgres
  - npm install
script:
  - npm run test
after_script: 
  - npm run coverage
  